### ISSUE TITLE
常用 mysql 语句有点问题

### ISSUE THREAD

**Issue by chenyuanqi** [TIGERB/easy-tips#13]
整理的还挺全面的~  
Mysql 常用语句里这个是不对的吧：  

> 列出表：DESC TABLES;  

列出表应该是 SHOW TABLES, 而查看表结构是 DESC table_name;

**Comment by TIGERB** [comment]
丫，记得以前改了，估计漏掉了，哈哈，谢谢，新年快乐~

**Comment by TIGERB** [comment]
已纠正 thx~
