### ISSUE TITLE
Why get & getset twice to get locktime?

### ISSUE THREAD

**Issue by cnkuangshi** [TIGERB/easy-tips#16]
How can I do like this?
``
$timeout = 500;
do {
 $microtime = explode(' ', microtime());
 $microtime = (int)round(($microtime[1]+$microtime[0])*1000, 0);
 $microtimeout = $microtime+$timeout+1;
 // 上锁
 $isLock = $redis->setnx('lock.count', $microtimeout);
 if (!$isLock) {
   // 超时判断
   $previousTime = $redis->getset('lock.count', $microtimeout);
   if ($previousTime <= $microtime) {
     // 超时
     break;
   }
 }
} while (!$isLock);
``

**Comment by TIGERB** [comment]
You are right, My problem~

thx~

哈哈～

**Comment by TIGERB** [comment]
Fix it ~

**Comment by TIGERB** [comment]
不对，貌似还是有问题。。不先get判断是否超时，直接getset不久都持有锁了？
