### ISSUE TITLE
你就不能把运行次数弄大一点儿？

### ISSUE THREAD

**Issue by wclssdn** [TIGERB/easy-tips#23]
没见过benchmark就跑这么几次的。。。。 http://tigerb.cn/2017/03/04/php-magic-function

**Comment by TIGERB** [comment]
哈哈，第一次搞，10000次我觉得可以了

很多不足，还希望能和你们多学习～

thx~

**Comment by wclssdn** [comment]
你没跑过benchmark么？ 你看看结果，是跑了多少次。。。

**Comment by TIGERB** [comment]
木有啊，我现在很水的，哈哈，还在学习中

谢了～

**Comment by slawdan** [comment]
由于你的 getmicrotime 函数本身处理了：

1. 1次 explode
2. 2次 string 隐式转换为 int
3. 一次“+”和一次“*”运算

建议还是把 getmicrotime 实现改为：

```php
function getmicrotime($accuracy=1000000) {
    return microtime(1) * $accuracy;
}
```

用来记时的函数，相对于被测试的语句，开销越小，计时才会越准确……

**Comment by TIGERB** [comment]
谢谢你的建议，学习了～
