### ISSUE TITLE
悲观锁

### ISSUE THREAD

**Issue by caoqiang1990** [TIGERB/easy-tips#24]
![image](https://cloud.githubusercontent.com/assets/22781493/23822971/e26834ea-0692-11e7-9d59-3dc715d56545.png)
当超时时间小于当前时间，说明超时，应该解锁。

**Comment by TIGERB** [comment]
下面可以抢锁了～

**Comment by slawdan** [comment]
这块儿写的逻辑有严重问题……

1. 22行 $getTime 和 $microtime 的大小关系判断写反了
2. 29行，在超时抢锁时，getset 会不断的将（当前）未拿到锁的新的 timeout 写入lock.count，如果先抢到锁的进程如果没有 del 掉 lock.count，那么当前进程永远都会 wait……

所以这个实现明显是有问题的……

写这么多，真正起作用的还是 setnx ……处理小于1秒级的超时时间的锁，就好好自行实现个 timeout ……你这个实现错误百出，不如直接用 expire 让 redis 帮你处理超时呢……

**Comment by TIGERB** [comment]
谢谢～
- 22行：的确写反了，可能上次删了，加的时候没注意
- 29行：判断是超时之后才去抢锁，getset之间毫秒级别时间差，一般情况可以忽略

学习了～

**Comment by TIGERB** [comment]
fix it ~

**Comment by slawdan** [comment]
关于 29行的问题，你在  36 行加入 `sleep(10)` 以模拟长时间占锁的情况，就会发现等待锁的进程一定要等到先拿到锁的进程完全退出才能拿到锁，抢锁机制是无效的。

所以才说你真正起作用的只是 setnx 而已……

**Comment by TIGERB** [comment]
别的进程getset拿不到锁？

我看看～

谢谢～

**Comment by slawdan** [comment]
我重新验证了一下，getset 的逻辑本身没啥问题。问题出在 setnx 时的类型转换上。

setnx 进去的 timeout 被转成了科学计数法表示导致后续比较时精度丢失。我的 PHP 版本是 5.6

试了一下，两个办法可以解决：

1. 17行 (microtime(true) % 1000) * 1000 强制把高位数字去掉
2. 20行 setnx(..., strval($microtimeout)); 强转为数字表示的字符串

**Comment by TIGERB** [comment]
学习精神啊～

想你学习～

谢谢～

我看看～
