### ISSUE TITLE
引擎部分，聚簇索引上下文介绍不一致

### ISSUE THREAD

**Issue by onlyshow** [TIGERB/easy-tips#55]
[https://github.com/TIGERB/easy-tips/blob/master/mysql/base.md#%E5%BC%95%E6%93%8E](url)

**Comment by TIGERB** [comment]
稍等，我看看

**Comment by TIGERB** [comment]
看了下，没太明白你的意思，幸苦详细说下，谢谢～

**Comment by TIGERB** [comment]
看见了，上面写反了，才发现，谢谢了～

**Comment by TIGERB** [comment]
修复了～
