### ISSUE TITLE
php模板模式在php5.

### ISSUE THREAD

**Issue by ooing** [TIGERB/easy-tips#6]
Default value for parameters with a class type hint can only be NULL D:\www\easy-tips\template\SmsCompanyOne.php on line 32

**Comment by ooing** [comment]
Default value for parameters with a class type hint can only be NULL  D:\www\easy-tips\template\SmsCompanyOne.php on line 32

**Comment by TIGERB** [comment]
got it

**Comment by TIGERB** [comment]
fix it, thx~
