### ISSUE TITLE
tcp/ip网络模型想补充下

### ISSUE THREAD

**Issue by yahaphper** [TIGERB/easy-tips#74]
TCP/IP
    应用层(http/https/websocket/ftp...) => 定义：文本传输协议，主要传输数据为报文
      |
    传输层(tcp/udp) => 定义：端口，主要传输数据为包，再次中会实现分组交换或电路交换
      |
    网络层(ip)　=> 定义：IP，主要传输数据为数据帧，典型有arp协议，再此中会添加ip->mac映射关系，crc冗余校验帧完整性等
      |
    网络接口层(光缆/电缆/交换机/路由/终端...) => 定义：物理   主要传输数据为二进制比特流

**Comment by TIGERB** [comment]
欢迎pr~

谢谢哈～
