### ISSUE TITLE
类私有成员属性，建议下划线小写开头驼峰

### ISSUE THREAD

**Issue by xingwenge** [TIGERB/easy-tips#8]
符合PSR-1/PSR-2的PHP编程规范实例
easy-tips/standard.php里，提到
 /**
   * 属性描述.
   *
   * @var string
   */
  private $_privateNameTest = ''; // 类私有成员属性，建议下划线小写开头驼峰

在[ psr-2标准](http://www.php-fig.org/psr/psr-2/)里，是不应该有下划线的。

`
4.2. Properties

Visibility MUST be declared on all properties.

The var keyword MUST NOT be used to declare a property.

There MUST NOT be more than one property declared per statement.

**Property names SHOULD NOT be prefixed with a single underscore to indicate protected or private visibility.**

A property declaration looks like the following.
`

**Comment by TIGERB** [comment]
这个是在psr下，我个人建议的写法，个人觉得可读性会比较好，THX~

只是建议 哈哈～ 
最终，跟团队走就好了～

谢谢～

**Comment by TIGERB** [comment]
已纠正，加上了【个人建议】，THX~
